### ISSUE TITLE
【要望】前奏・休憩地帯・後奏 などにおけるHMDの動きを累計値から除外するオプションの追加

### ISSUE THREAD

**Issue by yatakabs** [denpadokei/HeadDistanceTravelled#1]
## 背景
ぼっ立ちビーセイ度を測る指標として、一般的にノーツ・ボム・壁などのオブジェクトが存在しない前奏・休憩地帯・後奏において一人称視点の揺らぎを無視することが多いです。そのため、こういった場面においてはHMDの移動距離の累積を一時停止、もしくは最終的な集計の際に除外するオプションがあると、ぼっ立ち度を評価する上でとても助かります。

## 提供されるとうれしい機能
- ゲーム上プレイに影響するオブジェクトが存在しない間における移動距離累積処理の停止機能
- 同設定UI
    - 同機能のオン・オフ設定

**Comment by denpadokei** [comment]
前奏と後奏については実装しましょう。

休憩地帯については個人的には計測したいですね。休憩中も動いてない人もいるので。

**Comment by yatakabs** [comment]
前奏・後奏いについてご対応いただけるとのこと、ありがとうございます。
休憩地帯については「動くな」というルールでも大きな違和感はありませんので、妥当かと思います。
どうぞよろしくお願いします。
