### ISSUE TITLE
【要望】1.18.* をサポートしたい（1.20.0のmod環境が十分に整うまで当面の間）

### ISSUE THREAD

**Issue by yatakabs** [denpadokei/HeadDistanceTravelled#3]
## 概要
`1.20.0` における Mod 環境が未だ十分に整備されていないため、`1.20.0` に加え `1.18.*` のサポートを追加したい。

## 詳細
- `1.18.*` と `1.20.0` では依存ライブラリのバージョン及び Beat Saber 自体の依存クラスなど大きく差異があるため、ビルド定義を追加し個別のアセンブリとしてリリースすることが保守上・配布上好ましいと思う。
- もし `1.18.*` のサポートを追加したとしても、`1.20.0` にて mod 環境が十分に整ってきたといえる時点においてこれを打ち切ってもよいと思う。
  - Score Saber が近々 `1.20.0` より前のバージョンについてスコア送信を無効にする見込みであるため、それを目安にしてもよいかと思う。

## 備考
`1.20.0` に加え過去バージョンのサポートを維持することは開発コスト上も好ましくないと考えるので、本issueに紐付くPullRequestを直接取り込まないという選択をされた場合それを尊重します。
その場合、下記のようにForkしたリポジトリを元に `1.18.*` 対応版を個別にリリースをする形を取らせていただけますと幸いです。
https://github.com/yatakabs/HeadDistanceTravelled/releases/tag/0.0.2-yas

※ 参考として一つリリースを作成しましたが、問題などありましたらご指摘いただければ削除など対応いたします。

**Comment by denpadokei** [comment]
要望ありがとうございます。    
  
やすさんの考えている通り、1.20.0ではまだまだModもそろっていないし、すでに出ているModにも不具合があったりと不安定である点には同意です。そのため、私の方でも一つ前の1.19.0をサポートするように0.0.1を作成しました。

ただ、1.18.0以下ではゲームバージョンに加えて、SiraUtilのバージョンも変わっているため私の方ではサポートしませんでした。  
私は過去バージョンのサポートについては基本的には行いません。例外的にその人専用のワンオフModや、ビー祭等で使用したいから個人的に欲しいというDMが来た時は喜んで対応する方針をとっています。

特にこのModはSongRequestManagerやEnhanceStreamChatのように万人に使ってもらうようなModでもないため、個別対応でいいかなと考えています。  
  
やすさんの方で過去バージョン用をリリースしたり、独自機能を加えて改造すること自体は全く問題ありません。そのためのMITライセンスなので。    
  
今回の過去バージョンの対応につきましては機能追加やバグ修正とは少し状況が異なるためこのままCloseさせていただきます。

**Comment by yatakabs** [comment]
ご回答ありがとうございます。理解できますし明快なご説明ありがとうございます。
僕が1.18.3へバックポートする動機も自分用ですので、当面の間こちら側での対応を続けさせていただきます。
